spin_manifest_version = 2

[application]
name = "finicky-whiskers-www-redirect"
version = "0.1.0"
description = "Redirect www.finickywhiskers.com to finickywhiskers.com"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]

[[trigger.http]]
id = "trigger-redirect"
component = "redirect"
route = "/..."

[component.redirect]
source = { url = "https://github.com/fermyon/spin-redirect/releases/download/v0.1.0/redirect.wasm", digest = "sha256:8bee959843f28fef2a02164f5840477db81d350877e1c22cb524f41363468e52" }
environment = { DESTINATION = "https://finickywhiskers.com" }