name: Dispatch Event

on:
  push:
    branches: [main]
    tags: ["v*"]

jobs:
  dispatch:
    name: Dispatch finicky-whiskers-updated event
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'fermyon' }}
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DEST_REPO_ACCESS_TOKEN }}
          repository: ${{ secrets.DEST_REPO }}
          event-type: finicky-whiskers-updated
          client-payload: '{"event_type": "finicky-whiskers-updated", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'